
package gestion_usuarios;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.ResultSet;

public class Inicio_de_Sesión extends javax.swing.JFrame {
    private Connection conexion;

    public Inicio_de_Sesión(Connection conex) {
        initComponents();
        this.conexion = conex;
        this.setLocationRelativeTo(this);
        
        SetImageLabel(jLabel6, "src/resources/Usuario.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @param args
     */
    @SuppressWarnings("unchecked")
    
    
    
    public void SetImageLabel(JLabel labelName , String root){
    ImageIcon image = new ImageIcon(root);
    Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
    labelName.setIcon(icon);
    this.repaint();
    
    
    }
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPasswordFieldContraseña = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(542, 348));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Inicio de Sesión");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(250, 20, 135, 22);

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Bienvenido");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(250, 50, 103, 16);

        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldNombre);
        jTextFieldNombre.setBounds(210, 110, 135, 22);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Usuario");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(210, 80, 135, 24);

        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Contraseña");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(210, 150, 135, 16);

        jButton1.setBackground(new java.awt.Color(153, 0, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(220, 280, 120, 23);
        jPanel2.add(jPasswordFieldContraseña);
        jPasswordFieldContraseña.setBounds(210, 170, 135, 22);
        jPanel2.add(jLabel6);
        jLabel6.setBounds(190, 20, 50, 50);

        jButton2.setForeground(new java.awt.Color(153, 0, 255));
        jButton2.setText("Crea una");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(210, 230, 135, 16);

        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("¿No tienes una cuenta?");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(180, 210, 190, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    String nombre = jTextFieldNombre.getText().trim();
    String contraseña = new String(jPasswordFieldContraseña.getPassword()).trim();

    // Validar campos no vacíos
    if (nombre.isEmpty() || contraseña.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Debe completar ambos campos", "Advertencia", JOptionPane.WARNING_MESSAGE);
    return;
    }

    Connection conn = null;
    PreparedStatement pstmt = null;
    ResultSet rs = null;

    try {
    // Obtener conexión de tu clase BD
    conn = BD.conectar();
    
    // Consulta SQL para verificar credenciales y obtener el ID
    String sql = "SELECT ID_Usuario, Nombre, Contraseña FROM usuario WHERE Nombre = ? AND Contraseña = ?";
    
    pstmt = conn.prepareStatement(sql);
    pstmt.setString(1, nombre);
    pstmt.setString(2, contraseña);
    
    rs = pstmt.executeQuery();
    
    if (rs.next()) {
        // Obtener el ID del usuario
        int id = rs.getInt("ID_Usuario");
        
        
        // Crear y mostrar el menú pasando todos los datos necesarios
        Menu menu = new Menu(contraseña, nombre, id, conn);
        this.dispose();
        menu.setVisible(true);
    }
    else {
        // Credenciales incorrectas
        JOptionPane.showMessageDialog(this, "Los datos no coinciden. Vuelve a intentar.", 
                                    "Error", JOptionPane.ERROR_MESSAGE);
        
        // Limpiar campos para nuevo intento
        jPasswordFieldContraseña.setText("");
        jTextFieldNombre.requestFocus();
    }
    } catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, "Error al verificar credenciales: " + ex.getMessage(), 
                                "Error", JOptionPane.ERROR_MESSAGE);
    } finally {
    // Cerrar recursos
    try {
        if (rs != null) rs.close();
        if (pstmt != null) pstmt.close();
        if (conn != null) conn.close();
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al cerrar conexión: " + ex.getMessage(), 
                                    "Error", JOptionPane.ERROR_MESSAGE);
    }
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        Registrarse obj = new Registrarse();
        
        this.setVisible(false);
        obj.setVisible(true);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldContraseña;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
