/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gestion_usuarios;


import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Connection;
import javax.swing.JOptionPane;



public class ProcesoNaturalizacion extends javax.swing.JFrame {

    private String contraseña;
    private String nombre;
    private int id;
    private Connection conex;
    
    public ProcesoNaturalizacion(String contraseña, String nombre, int id , Connection conex) {
        initComponents();
        this.setLocationRelativeTo(this);
        this.conex = conex;
        this.id = id;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Elegir Proceso");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 20, 130, 25);

        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Elige el Proceso que más se adecue a tu situación");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 50, 300, 16);

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton5.setText("Ver Requerimientos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(320, 260, 130, 21);

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton6.setText("Ver Requerimientos");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(90, 160, 130, 21);

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton7.setText("Ver Requerimientos");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(90, 260, 130, 21);

        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton8.setText("Ver Requerimientos");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(320, 160, 130, 21);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tener hijos Mexicanos");
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1);
        jLabel1.setBounds(270, 200, 230, 90);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Padres Mexicanos");
        jLabel4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4);
        jLabel4.setBounds(270, 100, 230, 90);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Latinoamericano");
        jLabel5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jLabel5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel5KeyPressed(evt);
            }
        });
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 100, 230, 90);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Matrimonio con Mexican@");
        jLabel6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 200, 230, 90);

        jLabel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 100, 480, 220);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton2.setText("<Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 10, 70, 21);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    try {
        String nombreMetodo = "Por Latinoamericano";
        
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/relacional", "root", "Admin!01");
        
        String sql = "SELECT Requisitos FROM metodo_naturalizacion WHERE Nombre_Metodo = ?";
        PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, nombreMetodo);
        
        ResultSet rs = pstmt.executeQuery();
        
        if (rs.next()) {
            String requisitos = rs.getString("Requisitos");
            
            JOptionPane.showMessageDialog(this, "Requerimientos:\n" + requisitos.replace(",", "\n"), 
                                        "Requerimientos", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se encontraron requisitos para este método.", 
                                        "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        rs.close();
        pstmt.close();
        conn.close();
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al consultar la base de datos: " + ex.getMessage(), 
                                    "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
try {
        String nombreMetodo = "Por Padres Mexicanos";
        
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/relacional", "root", "Admin!01");
        
        String sql = "SELECT Requisitos FROM metodo_naturalizacion WHERE Nombre_Metodo = ?";
        PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, nombreMetodo);
        
        ResultSet rs = pstmt.executeQuery();
        
        if (rs.next()) {
            String requisitos = rs.getString("Requisitos");
            
            JOptionPane.showMessageDialog(this, "Requerimientos:\n" + requisitos.replace(",", "\n"), 
                                        "Requerimientos", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se encontraron requisitos para este método.", 
                                        "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        rs.close();
        pstmt.close();
        conn.close();
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al consultar la base de datos: " + ex.getMessage(), 
                                    "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    } 
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
try {
        String nombreMetodo = "Por Matrimonio con Mexican@";
        
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/relacional", "root", "Admin!01");
        
        String sql = "SELECT Requisitos FROM metodo_naturalizacion WHERE Nombre_Metodo = ?";
        PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, nombreMetodo);
        
        ResultSet rs = pstmt.executeQuery();
        
        if (rs.next()) {
            String requisitos = rs.getString("Requisitos");
            
            JOptionPane.showMessageDialog(this, "Requerimientos:\n" + requisitos.replace(",", "\n"), 
                                        "Requerimientos", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se encontraron requisitos para este método.", 
                                        "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        rs.close();
        pstmt.close();
        conn.close();
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al consultar la base de datos: " + ex.getMessage(), 
                                    "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    } 
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    try {
        String nombreMetodo = "Por Hijos Mexicanos";
        
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/relacional", "root", "Admin!01");
        
        String sql = "SELECT Requisitos FROM metodo_naturalizacion WHERE Nombre_Metodo = ?";
        PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, nombreMetodo);
        
        ResultSet rs = pstmt.executeQuery();
        
        if (rs.next()) {
            String requisitos = rs.getString("Requisitos");
            
            JOptionPane.showMessageDialog(this, "Requerimientos:\n" + requisitos.replace(",", "\n"), 
                                        "Requerimientos", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se encontraron requisitos para este método.", 
                                        "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        rs.close();
        pstmt.close();
        conn.close();
        
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error al consultar la base de datos: " + ex.getMessage(), 
                                    "Error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace();
    }  
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        Menu obj = new Menu(contraseña , nombre, id, conex);

        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel5KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5KeyPressed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
    String proceso = "Por Latinoamericano";
    
Connection conexion = null;
try {
    String url = "jdbc:mysql://localhost:3306/relacional";
    String usuario = "root";
    String contraseñaDB = "Admin!01";
    
    conexion = DriverManager.getConnection(url, usuario, contraseñaDB);
    
    String sql = "UPDATE usuario SET Método_Actual = ? WHERE ID_Usuario = ?";
    PreparedStatement pst = conexion.prepareStatement(sql);
    pst.setString(1, proceso);
    pst.setInt(2, id);
    
    int rowsAffected = pst.executeUpdate();
    
    if (rowsAffected > 0) {
        System.out.println("Método actualizado correctamente");
    } else {
        System.out.println("No se encontró el usuario con ID: " + id);
    }
    
    pst.close();
    
    Opc_Proceso obj = new Opc_Proceso(proceso, contraseña, nombre, id, conexion);
    obj.setVisible(true);
    this.setVisible(false);
    
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(null, "Error de base de datos: " + ex.getMessage());
}
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
    
        String proceso = "Por Padres Mexicanos";
    
Connection conexion = null;
try {
    String url = "jdbc:mysql://localhost:3306/relacional";
    String usuario = "root";
    String contraseñaDB = "Admin!01";
    
    conexion = DriverManager.getConnection(url, usuario, contraseñaDB);
    
    String sql = "UPDATE usuario SET Método_Actual = ? WHERE ID_Usuario = ?";
    PreparedStatement pst = conexion.prepareStatement(sql);
    pst.setString(1, proceso);
    pst.setInt(2, id);
    
    int rowsAffected = pst.executeUpdate();
    
    if (rowsAffected > 0) {
        System.out.println("Método actualizado correctamente");
    } else {
        System.out.println("No se encontró el usuario con ID: " + id);
    }
    
    pst.close();
    
    Opc_Proceso obj = new Opc_Proceso(proceso, contraseña, nombre, id, conexion);
    obj.setVisible(true);
    this.setVisible(false);
    
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(null, "Error de base de datos: " + ex.getMessage());
}
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
    
        String proceso = "Por Matrimonio con Mexican@";
    
Connection conexion = null;
try {
    String url = "jdbc:mysql://localhost:3306/relacional";
    String usuario = "root";
    String contraseñaDB = "Admin!01";
    
    conexion = DriverManager.getConnection(url, usuario, contraseñaDB);
    
    String sql = "UPDATE usuario SET Método_Actual = ? WHERE ID_Usuario = ?";
    PreparedStatement pst = conexion.prepareStatement(sql);
    pst.setString(1, proceso);
    pst.setInt(2, id);
    
    int rowsAffected = pst.executeUpdate();
    
    if (rowsAffected > 0) {
        System.out.println("Método actualizado correctamente");
    } else {
        System.out.println("No se encontró el usuario con ID: " + id);
    }
    
    pst.close();
    
    Opc_Proceso obj = new Opc_Proceso(proceso, contraseña, nombre, id, conexion);
    obj.setVisible(true);
    this.setVisible(false);
    
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(null, "Error de base de datos: " + ex.getMessage());
}
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
    
        String proceso = "Por Hijos Mexicanos";
    
Connection conexion = null;
try {
    String url = "jdbc:mysql://localhost:3306/relacional";
    String usuario = "root";
    String contraseñaDB = "Admin!01";
    
    conexion = DriverManager.getConnection(url, usuario, contraseñaDB);
    
    String sql = "UPDATE usuario SET Método_Actual = ? WHERE ID_Usuario = ?";
    PreparedStatement pst = conexion.prepareStatement(sql);
    pst.setString(1, proceso);
    pst.setInt(2, id);
    
    int rowsAffected = pst.executeUpdate();
    
    if (rowsAffected > 0) {
        System.out.println("Método actualizado correctamente");
    } else {
        System.out.println("No se encontró el usuario con ID: " + id);
    }
    
    pst.close();
    
    Opc_Proceso obj = new Opc_Proceso(proceso, contraseña, nombre, id, conexion);
    obj.setVisible(true);
    this.setVisible(false);
    
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(null, "Error de base de datos: " + ex.getMessage());
}
    }//GEN-LAST:event_jLabel1MouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
