package gestion_usuarios;

import java.sql.*;
import java.util.*;
import javax.swing.*;

public class statsexam extends javax.swing.JFrame {
   private int id;
private Connection conex;
private String contraseña;
private String nombre;

// Clase interna para almacenar los datos del examen
private static class ResultadoExamen {
    private final int idResultado;
    private final int puntaje;
    private final int idExamen;
    
    public ResultadoExamen(int idResultado, int puntaje, int idExamen) {
        this.idResultado = idResultado;
        this.puntaje = puntaje;
        this.idExamen = idExamen;
    }
    
    public int getIdResultado() { return idResultado; }
    public int getPuntaje() { return puntaje; }
    public int getIdExamen() { return idExamen; }
}

public statsexam(int id, Connection conex, String contraseña, String nombre) {
    initComponents();
    this.setLocationRelativeTo(this);
    this.id = id;
    this.conex = conex;
    this.contraseña = contraseña;
    this.nombre = nombre;
    cargarUltimosExamenes();
}

private void cargarUltimosExamenes() {
    List<ResultadoExamen> resultados = obtenerUltimosExamenes();
    
    if (resultados.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No hay resultados de exámenes registrados", 
                                    "Información", JOptionPane.INFORMATION_MESSAGE);
        return;
    }
    
    // Arrays de JLabels para mostrar la información
    JLabel[] labelsPuntaje = {jLabel1, jLabel3, jLabel4, jLabel5, jLabel6};
    JLabel[] labelsExamen = {jLabel7, jLabel8, jLabel9, jLabel10, jLabel11};
    
    for (int i = 0; i < Math.min(resultados.size(), 5); i++) {
        ResultadoExamen resultado = resultados.get(i);
        
        
        // Mostrar puntaje obtenido
        labelsPuntaje[i].setText("Puntaje: " + resultado.getPuntaje() + "/10");
        
        // Convertir ID_Examen a nombre del examen
        String nombreExamen = convertirIdExamenANombre(resultado.getIdExamen());
        labelsExamen[i].setText("Examen: " + nombreExamen);
        
        // Hacer visibles los labels
        labelsPuntaje[i].setVisible(true);
        labelsExamen[i].setVisible(true);
    }
    
    // Ocultar labels sobrantes si hay menos de 5 exámenes
    for (int i = resultados.size(); i < 5; i++) {
        labelsPuntaje[i].setVisible(false);
        labelsExamen[i].setVisible(false);
    }
}

private List<ResultadoExamen> obtenerUltimosExamenes() {
    List<ResultadoExamen> resultados = new ArrayList<>();
    String sql = "SELECT ID_Resultado, Puntaje_Obtenido, ID_Examen " +
                 "FROM resultado_examen " +
                 "WHERE ID_Usuario = ? " +
                 "ORDER BY ID_Resultado DESC LIMIT 5";
    
    try (Connection nuevaConexion = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/relacional", 
            "root", 
            "Admin!01");
         PreparedStatement pstmt = nuevaConexion.prepareStatement(sql)) {
        
        pstmt.setInt(1, id);
        
        try (ResultSet rs = pstmt.executeQuery()) {
            while (rs.next()) {
                resultados.add(new ResultadoExamen(
                    rs.getInt("ID_Resultado"),
                    rs.getInt("Puntaje_Obtenido"),
                    rs.getInt("ID_Examen")
                ));
            }
        }
        
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, 
            "Error al cargar resultados:\n" + e.getMessage(), 
            "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    return resultados;
}

private String convertirIdExamenANombre(int idExamen) {
    switch(idExamen) {
        case 1: return "Historia de México";
        case 2: return "Geografia de México";
        case 3: return "Instituciones y gobierno";
        case 4: return "Cultura y tradiciones";
        case 5: return "Idioma español";
        case 6: return "Simbolos patrios";
        default: return "Examen desconocido";
    }
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(542, 348));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Estadisticas Exámen");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 10, 200, 25);

        jSeparator1.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(30, 100, 140, 10);

        jSeparator2.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(370, 100, 140, 10);

        jSeparator3.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(200, 100, 140, 10);

        jSeparator4.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(110, 240, 140, 10);

        jSeparator5.setForeground(new java.awt.Color(204, 204, 255));
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(280, 240, 140, 10);

        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(370, 70, 140, 30);

        jLabel11.setText("jLabel11");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(280, 210, 140, 30);

        jLabel8.setText("jLabel8");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(200, 70, 140, 30);

        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(110, 210, 140, 30);

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setText("Volver a intentar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(380, 150, 120, 23);

        jLabel4.setBackground(new java.awt.Color(204, 204, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel4);
        jLabel4.setBounds(360, 70, 160, 120);

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setText("Volver a intentar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(210, 150, 120, 23);

        jLabel3.setBackground(new java.awt.Color(204, 204, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel3);
        jLabel3.setBounds(190, 70, 160, 120);

        jButton3.setBackground(new java.awt.Color(204, 204, 255));
        jButton3.setText("Volver a intentar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(120, 290, 120, 23);

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 210, 160, 120);

        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 70, 140, 30);

        jButton4.setBackground(new java.awt.Color(204, 204, 255));
        jButton4.setText("Volver a intentar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(40, 150, 120, 23);

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 70, 160, 120);

        jButton5.setBackground(new java.awt.Color(204, 204, 255));
        jButton5.setText("Volver a intentar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(290, 290, 120, 23);

        jLabel6.setBackground(new java.awt.Color(204, 204, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel6);
        jLabel6.setBounds(270, 210, 160, 120);

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jButton6.setText("<Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(10, 10, 70, 21);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    
        MenuExamen obj = new MenuExamen(conex , id, contraseña, nombre);
        
        obj.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
        MenuExamen obj = new MenuExamen(conex , id, contraseña, nombre);
        
        obj.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
        MenuExamen obj = new MenuExamen(conex , id, contraseña, nombre);
        
        obj.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    
        MenuExamen obj = new MenuExamen(conex , id, contraseña, nombre);
        
        obj.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    
        MenuExamen obj = new MenuExamen(conex , id, contraseña, nombre);
        
        obj.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        Menu obj = new Menu(contraseña , nombre, id, conex);

        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    // End of variables declaration//GEN-END:variables
}
